<a href="https://colab.research.google.com/github/kevinaldyansyah/SPK-with-python/blob/main/Moora.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Membuat Label untuk benefit dan cost
# Benefit = 1
# Cost = 0
# Label untuk C1, C2, C3, C4, C5, C6 secara berutan

label = [1, 1, 1, 0]

In [2]:
# Implementasi Matrix Pada Python
# Kita akan menggunakan bantuan Numpy untuk membuat 2d array

import numpy as np

init_matrix = np.array([[3,2,4,2], [4,3,3,2], [3,4,3,1], [3,2,1,3]])

print(init_matrix) #cek hasil matrix

[[3 2 4 2]
 [4 3 3 2]
 [3 4 3 1]
 [3 2 1 3]]


In [4]:

# Pada modul ini akan diterapkan normalisasi matrix sesuai dengan persamaan
# Kita akan membuat fungsi yang akan menerima paramater berupa array 2d
import math

def normalization(matrix):
    # Transpose Decision Matrix
    matrix = matrix.transpose()
    row_values = []
    norm_matrix = []
    
    for i in range(matrix.shape[0]): # Looping per baris (kriteria)
        # Menghitung sum tiap x_{ij}^2
        sum_row = sum([pow(x,2) for x in matrix[i]])
        
        for j in range(matrix[i].shape[0]): # Looping per kolom (alternatif)
            # membangi nilai asli x_{ij} dengan hasil akar
            r_value = matrix[i][j] / math.sqrt(sum_row)
            
            # Masukkan hasil normalisasi ke list tiap baris
            row_values.append(r_value)
        
        #Masukkan hasil normalisasi per baris ke matrix normalisasi
        norm_matrix.append(row_values)
        
        #Kosongkan list normalisasi perbaris
        row_values = []
            
    # Ubah dalam bentuk numpy array
    norm_matrix = np.asarray(norm_matrix)
    
    # Return dalam bentuk transporse agar kembali ke format awal
    return norm_matrix.transpose()

In [5]:
# Test fungsi normalisasi
n_matrix = normalization(init_matrix)

# Cetak hasil normalisasi
print(n_matrix)

[[0.45749571 0.34815531 0.6761234  0.47140452]
 [0.60999428 0.52223297 0.50709255 0.47140452]
 [0.45749571 0.69631062 0.50709255 0.23570226]
 [0.45749571 0.34815531 0.16903085 0.70710678]]


In [6]:

# Kalkulasi skor normalisasi terbobot

# Bobot untuk Kriteria C1, C2, C3, C4
c_weights = np.array([0.3, 0.3, 0.2, 0.2])

# Fungsi untuk kalkulasi matrix terbobot. Paramter yang diperlukan adalah nilai ternormalisasi dan bobot
# Untuk mempermudah perhitungan, lakukan operasi transpose pada matrix ternormalisasi.
# Ingat! Kriteria adalah baris, alternatif adalah kolom setelah proses transpose
def weighted_normalization(n_matrix, c_weights):
    # Buat salinan nilai ternormalisasi dan transpose
    norm_weighted = n_matrix.transpose()
    
    for i in range(c_weights.shape[0]): # Looping tiap kriteria
        # Kalkulasi normalisasi terbobot
        norm_weighted[i] = [r * c_weights[i] for r in norm_weighted[i]]
    
    # Ubah ke bentuk numpy array
    norm_weighted = np.asarray(norm_weighted)
    
    # Return ke dalam format matrix semula
    return norm_weighted.transpose()

In [7]:
# Test fungsi pembobotan
w_matrix = weighted_normalization(n_matrix, c_weights)

# Cetak hasil
print(w_matrix)

[[0.13724871 0.10444659 0.13522468 0.0942809 ]
 [0.18299828 0.15666989 0.10141851 0.0942809 ]
 [0.13724871 0.20889319 0.10141851 0.04714045]
 [0.13724871 0.10444659 0.03380617 0.14142136]]


In [8]:
def optimize_value(w_matrix, label):
    y_values = []
    
    for i in range(w_matrix.shape[0]):
        max_val = []
        min_val = []
        
        for j in range(w_matrix[i].shape[0]):
            # Hitung benefit
            if label[j] == 1:
                max_val.append(w_matrix[i][j])
            # Hitung cost
            else:
                min_val.append(w_matrix[i][j])
        
        y = sum(max_val) - sum(min_val)
        y_values.append(y)
    
    return np.asarray(y_values)

In [9]:
# Test fungsi nilai optimasi
result = optimize_value(w_matrix, label)

print(result)

[0.28263908 0.34680578 0.40041996 0.13408012]
